#!/bin/bash
# Waits for the distill run to finish, then finalizes and evaluates the student.
# Every stage is idempotent, so this can be re-run after a failure.
set -uo pipefail
R=/root/tts/TTS_training/pocket_TTS
F=$R/infer/final
RUN=/workspace/nepali_student_6l
TRAIN_PID=${TRAIN_PID:-597416}
VENV=$R/repo/.venv/bin/python3
ASR_VENV=/root/tts/TTS_training/synthetic_pipeline/asr_qc_service/.venv/bin/python3
SIM_VENV=/root/tts/TTS_training/synthetic_pipeline/vc_service/.venv/bin/python3

say() { echo "[$(date '+%H:%M:%S')] $*"; }

say "waiting for training pid $TRAIN_PID (step $(tail -1 $R/train_student.log | grep -o 'step [0-9]*'))"
while kill -0 "$TRAIN_PID" 2>/dev/null; do sleep 60; done
say "training process exited"
tail -3 $R/train_student.log

if [ ! -f "$RUN/checkpoint_00200000.pt" ]; then
  say "WARNING: checkpoint_00200000.pt missing -- the run did not reach max_steps."
  say "last checkpoint: $(ls -t $RUN/checkpoint_*.pt 2>/dev/null | head -1)"
fi

# 1. Snapshot the export. The process is gone, so this cannot be a torn read.
SNAP=$RUN/model_final_200k.safetensors
say "snapshotting $(ls -l $RUN/model.safetensors | awk '{print $5}') bytes -> $SNAP"
cp "$RUN/model.safetensors" "$SNAP.tmp" && mv "$SNAP.tmp" "$SNAP"

# 2. Point the inference config at it.
$VENV - "$SNAP" <<'PY'
import re, sys
p = "/root/tts/TTS_training/pocket_TTS/infer/nepali_student_6l.yaml"
s = open(p).read()
s = re.sub(r"# Weights are a snapshot.*?\n# a checkpoint write mid-training cannot cause a torn read\.\n",
           "# Weights are the final step-200000 export (EMA), snapshotted after the\n"
           "# training process exited.\n", s, flags=re.S)
s = re.sub(r"^weights_path: .*$", f"weights_path: {sys.argv[1]}", s, flags=re.M)
open(p, "w").write(s)
print("weights_path ->", sys.argv[1])
PY

# 2b. Purge prior outputs. gen_final.py skips ids that already have a wav, so any
# audio left from a smoke test would be silently carried into the final numbers --
# generated by DIFFERENT (earlier-step) student weights.
say "purging previous eval outputs"
rm -rf $F/wav $F/listen $F/wer.json $F/wer_ft.json $F/sim.json $F/bench.json

# 3. CPU speed, threads pinned (see cpu-bench-thread-oversubscription).
say "bench"
(cd $R/repo && OMP_NUM_THREADS=4 BENCH_THREADS=4 $VENV $R/infer/bench_student.py) 2>&1 | grep -E "RT|==|DONE"
cp $R/infer/bench/results.json $F/bench.json 2>/dev/null

# 4. Synthesize the held-out set with both models.
say "generating 100 held-out utterances x 2 models (CPU)"
(cd $R/repo && GEN_THREADS=16 OMP_NUM_THREADS=16 $VENV $F/gen_final.py) 2>&1 | grep -E "==|FAIL|/100|DONE"

# 5. Score. GPU is free now that training is done.
say "WER (faster-whisper large-v3-turbo, language=ne) -- weak on Nepali, kept as a baseline"
(cd $F && $ASR_VENV $F/score_wer.py) 2>&1 | grep -E "==|DONE|Error|Traceback"

# The Nepali-finetuned Whisper (10.98% WER) is the sharper instrument. It is private
# under the himalaya-ai org; the token in /root/.hf_whisper_ne_token reads it. Probe
# first and skip cleanly rather than failing the whole run.
if $SIM_VENV -c "
import os,sys,urllib.request
tf='/root/.hf_whisper_ne_token'
tok=open(tf).read().strip() if os.path.exists(tf) else os.environ.get('HF_TOKEN','')
r=urllib.request.Request('https://huggingface.co/api/models/himalaya-ai/whisper-large-v3-nepali-final',
                         headers={'Authorization':'Bearer '+tok})
try: urllib.request.urlopen(r,timeout=20); sys.exit(0)
except Exception: sys.exit(1)" 2>/dev/null; then
  say "WER (Nepali-finetuned whisper, doubled-sot prefix)"
  (cd $F && $SIM_VENV $F/score_wer_ft.py) 2>&1 | grep -E "==|DONE|Error|Traceback"
else
  say "SKIP finetuned-ASR WER: himalaya-ai/whisper-large-v3-nepali-final unreadable."
  say "     Base-whisper WER stands, and its real_human row shows how weak it is."
fi
say "speaker similarity (resemblyzer)"
(cd $F && $SIM_VENV $F/score_sim.py) 2>&1 | grep -E "==|DONE|Error|Traceback"

# 6. Blind A/B set + report.
$VENV $F/make_listen.py
$VENV $F/summarize.py
say "ALL DONE"
