# -*- coding: utf-8 -*-
"""notebook61a9e2a917 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pB7kPXdRicItaL648Aml_9IAqDbHzEU

# 🇳🇵 Indic Parler TTS — Nepali Finetuning (FULLY FIXED v3)

## ✅ All fixes over previous version:
2. **[CRITICAL] Removed `decoder_input_ids` from forward pass** — Parler TTS `forward()` builds its own shifted decoder inputs from `labels`. Passing both causes a double-input conflict.
3. **[CRITICAL] Fixed labels shape** — EnCodec returns `[B, num_codebooks, T]`. Labels must be `[B, num_codebooks, T]` (NOT transposed). The Parler loss internally iterates over codebooks.
4. Fixed autocast to `float16` (T4 has no native bfloat16 support — it emulates, causing slowdowns and instability).
5. Added GradScaler for float16 training stability.
6. Increased steps to 3000 with proper warmup.
7. Save desc_tokenizer alongside model checkpoint for complete inference.
8. Inference cell now reloads desc_tokenizer from checkpoint correctly.

> ⚠️ **GPU Required.** Go to `Runtime > Change runtime type > T4 GPU`

## 0. Environment Setup
"""

import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_USE_CUDA_DSA"]   = "1"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
# os.environ["WANDB_API_KEY"] = "your_key_here"
print("✅ Environment variables set")

# !pip install -q git+https://github.com/huggingface/parler-tts.git
# !pip install -q transformers>=4.40.0 datasets soundfile librosa accelerate huggingface_hub bitsandbytes
# !pip install "protobuf>=5.29.1,<6.0.0" --upgrade -q
# !pip install wandb -q


import google.protobuf
print(f"protobuf: {google.protobuf.__version__}")

from transformers import AutoTokenizer, EncodecModel, AutoProcessor
from parler_tts import ParlerTTSForConditionalGeneration
print("✅ All imports OK")

import transformers
print(transformers.__version__)

# from huggingface_hub import notebook_login
# notebook_login()

# from kaggle_secrets import UserSecretsClient
from huggingface_hub import login

# user_secrets = UserSecretsClient()
# hf_token = user_secrets.get_secret("HF_TOKEN")

hf_token = os.environ["HF_TOKEN"]
login(token=hf_token)

"""## 1. Config"""

# ── Edit these ───────────────────────────────────────────────────────────────
# HF_USERNAME      = "lilgoose777"
OUTPUT_REPO      = "milanakdj/indic-parler-tts-nepali-finetuned-dgx-v1"
DATASET_REPO     = "Titung/cc100-nepali-tts"
FINETUNE_BASE    = "ai4bharat/indic-parler-tts-pretrained"

# MAX_TRAIN_STEPS  = 1000
# BATCH_SIZE       = 2
# GRAD_ACCUM_STEPS = 4
# LEARNING_RATE    = 5e-6
# WARMUP_STEPS     = 600
# SAVE_STEPS       = 1000
# MAX_AUDIO_SEC    = 12
# MAX_AUDIO_TOKENS = 850
# MAX_TRAIN_STEPS  = 5000   # was 1000 -- too few to learn anything meaningful
# NUM_EPOCHS       = 1
# BATCH_SIZE       = 4      # keep
# GRAD_ACCUM_STEPS = 4      # keep (eff. batch = 8)
# LEARNING_RATE    = 1e-4   # keep
# WARMUP_STEPS     = 50    # was 600 -- should be ~5-10% of total steps, not 60%
# SAVE_STEPS      = 150   # Save & validate every N steps (~25% of your run)
# ZIP_EVERY_STEPS = 300   # Zip full checkpoints less frequently (saves time)

NUM_EPOCHS       = 3
BATCH_SIZE       = 32      # up from 4 — 128GB handles this easily
GRAD_ACCUM_STEPS = 2       # eff. batch = 64 (was 16)
LEARNING_RATE    = 5e-5    # scale up slightly with larger eff. batch
WARMUP_STEPS     = 200     # recalculate after knowing total steps
SAVE_STEPS       = 200
ZIP_EVERY_STEPS  = 600


ckpt_dir = "./checkpoints"
os.makedirs(ckpt_dir, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────

MAX_AUDIO_SEC    = 12     # keep
MAX_AUDIO_TOKENS = 550    # keep

print(f"Output repo  : {OUTPUT_REPO}")
print(f"Dataset      : {DATASET_REPO}")
print(f"Base model   : {FINETUNE_BASE}")
# print(f"Train steps  : {MAX_TRAIN_STEPS}")
print(f"Train EPOC  : {NUM_EPOCHS}")
print(f"Eff. batch   : {BATCH_SIZE * GRAD_ACCUM_STEPS}")
print(f"Warmup steps : {WARMUP_STEPS}")


import wandb

wandb.init(
    project = "tts",
    entity  = "himalaya-ai-lab",
    config  = {
        "num_epochs":       NUM_EPOCHS,
        "batch_size":       BATCH_SIZE,
        "name"    : "indic_tts_gb10-bf16-bs32-lr5e5",   
        "grad_accum_steps": GRAD_ACCUM_STEPS,
        "learning_rate":    LEARNING_RATE,
        "warmup_steps":     WARMUP_STEPS,
        "save_steps":       SAVE_STEPS,
        "zip_every_steps":  ZIP_EVERY_STEPS,
        "max_audio_sec":    MAX_AUDIO_SEC,
        "max_audio_tokens": MAX_AUDIO_TOKENS,
        "gpu":              "NVIDIA GB10 (DIGITS)",
    }
)

"""## 2. Load Parler TTS Model & Tokenizers"""

import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load in float32 — GradScaler handles precision; don't pre-cast to float16
print(f"\nLoading {FINETUNE_BASE}...")
ft_model = ParlerTTSForConditionalGeneration.from_pretrained(
    FINETUNE_BASE
).to(device)

# Prompt tokenizer (text-to-speak)
ft_tokenizer = AutoTokenizer.from_pretrained(FINETUNE_BASE)

# Description tokenizer (style description)
ft_desc_tokenizer = AutoTokenizer.from_pretrained(
    ft_model.config.text_encoder._name_or_path
)

# Enable gradient checkpointing to save VRAM
ft_model.gradient_checkpointing_enable()
if hasattr(ft_model, "decoder"):
    ft_model.decoder.gradient_checkpointing_enable()
ft_model.train()

parler_sample_rate = ft_model.config.sampling_rate
NUM_CODEBOOKS      = ft_model.config.decoder.num_codebooks

print(f"\n✅ Model loaded!")
print(f"   Params            : {sum(p.numel() for p in ft_model.parameters())/1e6:.0f}M")
print(f"   Sampling rate     : {parler_sample_rate} Hz")
print(f"   Num codebooks     : {NUM_CODEBOOKS}")
print(f"   BOS token         : {ft_model.config.decoder.bos_token_id}")
print(f"   EOS token         : {ft_model.config.decoder.eos_token_id}")
print(f"   PAD token         : {ft_model.config.decoder.pad_token_id}")
print(f"   VRAM used         : {torch.cuda.memory_allocated()/1e9:.2f} GB")

"""## 3. Load DAC


"""

from transformers import AutoModel, DacModel

DAC_MODEL_ID = "ylacombe/dac_44khz"
audio_decoder = DacModel.from_pretrained(DAC_MODEL_ID).to(device)
audio_decoder.eval()
for param in audio_decoder.parameters():
    param.requires_grad = False

def encode_audio_with_dac(audio_path):
    waveform, sr = torchaudio.load(audio_path)

    if sr != 44100:
        waveform = torchaudio.functional.resample(waveform, sr, 44100)

    # Mono
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0, keepdim=True)

    # DAC expects (batch, channels, time)
    waveform = waveform.unsqueeze(0).to(device)  # (1, 1, T)

    with torch.no_grad():
        encoded = audio_decoder.encode(waveform)

    # audio_codes shape: (batch, n_codebooks, time) → (9, T)
    audio_codes = encoded.audio_codes[0]

    assert audio_codes.shape[0] == 9, f"Expected 9 codebooks, got {audio_codes.shape[0]}"
    return audio_codes

"""## 4. Load & Prepare Dataset"""

from datasets import load_dataset, Audio
import numpy as np

print(f"Loading {DATASET_REPO}...")
nepali_ds = load_dataset(DATASET_REPO, split="train")
print(f"Dataset size : {len(nepali_ds)}")
print(f"Columns      : {nepali_ds.column_names}")
print(f"Sample       : {nepali_ds[0]}")

# Auto-detect column names
cols = nepali_ds.column_names
TEXT_COL = None
for c in ["text", "transcription", "sentence", "nepali_text"]:
    if c in cols:
        TEXT_COL = c
        break
if TEXT_COL is None:
    TEXT_COL = [c for c in cols if "audio" not in c.lower()][0]

AUDIO_COL = "audio" if "audio" in cols else [c for c in cols if "audio" in c.lower()][0]
print(f"Text column  : '{TEXT_COL}'")
print(f"Audio column : '{AUDIO_COL}'")

# Cast audio to 24kHz to match EnCodec + Parler
nepali_ds = nepali_ds.cast_column(AUDIO_COL, Audio(sampling_rate=parler_sample_rate))
print(f"✅ Audio resampled to {parler_sample_rate} Hz")

# def get_duration(sample):
#     arr = sample[AUDIO_COL]["array"]
#     sr  = sample[AUDIO_COL]["sampling_rate"]
#     return len(arr) / sr

# print("Filtering by audio length...")
# durations = [get_duration(s) for s in nepali_ds]
# keep = [i for i, d in enumerate(durations) if 0.5 < d <= MAX_AUDIO_SEC]
# nepali_ds_filtered = nepali_ds.select(keep)

nepali_ds_filtered = nepali_ds

print(f"Original     : {len(nepali_ds)}")
print(f"After filter : {len(nepali_ds_filtered)} (0.5s–{MAX_AUDIO_SEC}s)")

split    = nepali_ds_filtered.train_test_split(test_size=0.05, seed=42)
train_ds = split["train"]
val_ds   = split["test"]
print(f"Train: {len(train_ds)} | Val: {len(val_ds)}")

"""## 5. Dataset Class & Collator

Key changes from previous version:
- `encode_audio()` now uses `EncodecModel` instead of DAC
- Codes shape: `[num_codebooks, T]` per sample, stacked to `[B, num_codebooks, T]`
- Labels shape: `[B, num_codebooks, T]` — **NOT transposed** — Parler's loss iterates codebooks in dim=1
- `decoder_input_ids` is **not passed** to `forward()` — Parler builds shifted inputs from labels internally
"""

import torch
import torchaudio
import numpy as np
from torch.utils.data import Dataset
from transformers import DacModel

DESCRIPTION_TEMPLATES = [
    "A female speaker delivers clear Nepali speech at a normal pace. The recording is of very high quality.",
    "A female speaker speaks clearly and naturally in Nepali. The audio is clean with no background noise.",
    "A neutral speaker reads Nepali text at a steady pace. The recording quality is excellent.",
    "A female speaker delivers speech slowly and clearly in Nepali. Very high quality audio.",
]

TARGET_SR = 44100  # DAC 44khz


def encode_audio_with_dac(audio_array, sample_rate, dac_model, device):
    """
    Encode a 1D numpy audio array to DAC tokens.
    Returns codes: Tensor of shape [n_codebooks, T]
    """
    # Resample if needed
    if sample_rate != TARGET_SR:
        t = torch.tensor(audio_array).unsqueeze(0).float()
        t = torchaudio.functional.resample(t, sample_rate, TARGET_SR)
        audio_array = t.squeeze().numpy()

    audio_array = audio_array.astype(np.float32)

    # DAC expects (batch, channels, time)
    waveform = torch.tensor(audio_array).unsqueeze(0).unsqueeze(0)  # [1, 1, T]
    waveform = waveform.to(device)

    with torch.no_grad():
        encoded = dac_model.encode(waveform)
        # audio_codes: [B=1, n_codebooks, T]
        codes = encoded.audio_codes[0]  # → [n_codebooks, T]

    return codes.cpu()  # [n_codebooks, T]  — should be [9, T]


class NepaliTTSDataset(Dataset):
    def __init__(self, hf_dataset, text_col, audio_col,
                 tokenizer, desc_tokenizer,
                 dac_model,           # ← renamed from encodec_model
                 device,
                 max_text_len=128,
                 max_audio_tokens=None):
        self.ds                = hf_dataset
        self.text_col          = text_col
        self.audio_col         = audio_col
        self.tokenizer         = tokenizer
        self.desc_tokenizer    = desc_tokenizer
        self.dac_model         = dac_model   # ← renamed
        self.device            = device
        self.max_text_len      = max_text_len
        self.max_audio_tokens  = max_audio_tokens or MAX_AUDIO_TOKENS

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        sample     = self.ds[idx]
        text       = sample[self.text_col].strip()
        audio_info = sample[self.audio_col]

        # Tokenize the text-to-speak (prompt)
        prompt_enc = self.tokenizer(
            text,
            return_tensors="pt",
            max_length=self.max_text_len,
            truncation=True,
            padding="max_length",
        )

        # Tokenize the style description
        # desc     = DESCRIPTION_TEMPLATES[idx % len(DESCRIPTION_TEMPLATES)]
        desc = "Shristi speaks with a deep, formal Nepali voice. Her speech is clear, steady and authoritative with natural pacing in a quiet noise-free environment."
        desc_enc = self.desc_tokenizer(
            desc,
            return_tensors="pt",
            max_length=256,
            truncation=True,
            padding="max_length",
        )

        # Encode audio with DAC
        audio_array = audio_info["array"]
        sr          = audio_info["sampling_rate"]
        codes = encode_audio_with_dac(
            audio_array, sr,
            self.dac_model,
            self.device
        )  # [9, T]

        # Truncate to max length (leave 1 slot for EOS)
        if codes.shape[1] > self.max_audio_tokens - 1:
            codes = codes[:, :self.max_audio_tokens - 1]

        # Append EOS (1024) to every codebook row
        eos_col = torch.full((codes.shape[0], 1), 1024, dtype=codes.dtype)
        codes   = torch.cat([codes, eos_col], dim=1)  # [9, T+1]

        # Slice to Parler's expected number of codebooks
        codes = codes[:NUM_CODEBOOKS, :]  # [NUM_CODEBOOKS, T+1]

        return {
            "input_ids":           prompt_enc.input_ids.squeeze(0),
            "attention_mask":      prompt_enc.attention_mask.squeeze(0),
            "desc_input_ids":      desc_enc.input_ids.squeeze(0),
            "desc_attention_mask": desc_enc.attention_mask.squeeze(0),
            "audio_codes":         codes,                                # [9, T]
        }


print("✅ NepaliTTSDataset defined")
print(f"   NUM_CODEBOOKS    : {NUM_CODEBOOKS}")
print(f"   MAX_AUDIO_TOKENS : {MAX_AUDIO_TOKENS}")
print(f"   TARGET_SR        : {TARGET_SR}")

import torch.multiprocessing as mp
mp.set_start_method('spawn', force=True)  # At very top of notebook

import torch.nn.functional as F
from torch.utils.data import DataLoader

def collate_fn(batch):
    """
    decoder_input_ids → [B, num_codebooks, T]  (model transposes internally)
    labels            → [B, T, num_codebooks]  (model expects this layout for loss)
    These two are intentionally asymmetric — that's the Parler forward() contract.
    Pad token: 1025 (bos_token_id) — NOT 1024 which is EOS and contributes to loss.
    """
    max_audio_len = max(b["audio_codes"].shape[1] for b in batch)
    num_cb        = batch[0]["audio_codes"].shape[0]
    padded_codes, decoder_masks = [], []
    for b in batch:
        T   = b["audio_codes"].shape[1]
        pad = max_audio_len - T
        pc  = F.pad(b["audio_codes"], (0, pad), value=1025)  # (num_cb, max_T)
        padded_codes.append(pc)
        decoder_masks.append(
            F.pad(torch.ones(T, dtype=torch.long), (0, pad), value=0)
        )
    decoder_input_ids = torch.stack(padded_codes)         # (B, C, T)
    dec_mask          = torch.stack(decoder_masks)        # (B, T)
    labels = decoder_input_ids.permute(0, 2, 1).clone()  # (B, T, C)
    labels[labels == 1025] = -100
    return {
        "input_ids":              torch.stack([b["input_ids"]          for b in batch]),
        "attention_mask":         torch.stack([b["attention_mask"]      for b in batch]),
        "desc_input_ids":         torch.stack([b["desc_input_ids"]      for b in batch]),
        "desc_attention_mask":    torch.stack([b["desc_attention_mask"] for b in batch]),
        "decoder_input_ids":      decoder_input_ids,
        "decoder_attention_mask": dec_mask,
        "labels":                 labels,
    }

train_dataset = NepaliTTSDataset(
    train_ds, TEXT_COL, AUDIO_COL,
    ft_tokenizer, ft_desc_tokenizer,
    audio_decoder,   # ← updated
    device
)
val_dataset = NepaliTTSDataset(
    val_ds, TEXT_COL, AUDIO_COL,
    ft_tokenizer, ft_desc_tokenizer,
    audio_decoder,   # ← updated
    device
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                          shuffle=True,  num_workers=0, collate_fn=collate_fn)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE,
                          shuffle=False, num_workers=0, collate_fn=collate_fn)

print(f"✅ Datasets ready")
print(f"   Train: {len(train_dataset)} samples, {len(train_loader)} batches")
print(f"   Val  : {len(val_dataset)} samples,   {len(val_loader)} batches")

"""## 5b. Sanity Check — Batch Shapes & Loss Before Training"""

print("Running sanity check on one batch...")
sample_batch = next(iter(train_loader))
sample_batch = {k: v.to(device) for k, v in sample_batch.items()}

print("\n=== Batch shapes ===")
for k, v in sample_batch.items():
    print(f"  {k:30s}: {tuple(v.shape)}")

print("\n=== Token ranges ===")
real_labels = sample_batch["labels"][sample_batch["labels"] != -100]
print(f"  labels (excl -100) min/max : {real_labels.min().item()} / {real_labels.max().item()}")
print(f"  labels all -100?           : {real_labels.numel() == 0}")
print(f"  num real label tokens      : {real_labels.numel()}")

print("\n=== Float32 forward pass (no autocast) ===")
ft_model.eval()
with torch.no_grad():
    out_fp32 = ft_model(
        input_ids=             sample_batch["desc_input_ids"],
        attention_mask=        sample_batch["desc_attention_mask"],
        prompt_input_ids=      sample_batch["input_ids"],
        prompt_attention_mask= sample_batch["attention_mask"],
        decoder_attention_mask=sample_batch["decoder_attention_mask"],
        labels=                sample_batch["labels"],
    )
print(f"  Loss (float32): {out_fp32.loss.item():.4f}")

print("\n=== Float16 autocast forward pass ===")
with torch.no_grad():
    with torch.amp.autocast("cuda", dtype=torch.float16):
        out_fp16 = ft_model(
            input_ids=             sample_batch["desc_input_ids"],
            attention_mask=        sample_batch["desc_attention_mask"],
            prompt_input_ids=      sample_batch["input_ids"],
            prompt_attention_mask= sample_batch["attention_mask"],
            decoder_attention_mask=sample_batch["decoder_attention_mask"],
            labels=                sample_batch["labels"],
        )
print(f"  Loss (float16): {out_fp16.loss.item():.4f}")

# assert not torch.isnan(out_fp32.loss), "❌ NaN loss in float32! Check your data pipeline."
# assert not torch.isnan(out_fp16.loss), "❌ NaN loss in float16! Use float32 training only."
print("\n✅ Sanity check PASSED — losses are finite. Safe to train.")
ft_model.train()

"""## 6. Optimizer & Scheduler"""

from transformers import get_linear_schedule_with_warmup
try:
    import bitsandbytes as bnb
except ImportError:
    import subprocess
    subprocess.run(["pip", "install", "-q", "bitsandbytes"], check=True)
    import bitsandbytes as bnb

# Cast model to bfloat16 first
ft_model = ft_model.to(torch.bfloat16)

optimizer = bnb.optim.AdamW8bit(
    [p for p in ft_model.parameters() if p.requires_grad],
    lr=LEARNING_RATE, weight_decay=0.01, eps=1e-8
)

# compute total steps from epochs after you know the dataset size
steps_per_epoch = len(train_loader) // GRAD_ACCUM_STEPS
MAX_TRAIN_STEPS = NUM_EPOCHS * steps_per_epoch   # kept for scheduler only


scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=WARMUP_STEPS,
    num_training_steps=MAX_TRAIN_STEPS,
)
# No GradScaler needed for bfloat16
if 'scaler' in globals():
    del scaler

print("✅ Optimizer + Scheduler ready (bfloat16 — no scaler)")
print(f"   Peak LR      : {LEARNING_RATE:.1e}")
print(f"   Warmup steps : {WARMUP_STEPS}")
print(f"   Total steps  : {MAX_TRAIN_STEPS}")
print(f"   VRAM used    : {torch.cuda.memory_allocated()/1e9:.2f} GB")
print(f"   Model dtype  : {set(p.dtype for p in ft_model.parameters())}")
print(f"   Has scaler   : {'scaler' in globals()}")

"""## 7. Training Loop"""

# Run this before training
dtypes = set(p.dtype for p in ft_model.parameters())
print("Model weight dtypes:", dtypes)

print("Model dtype:", set(p.dtype for p in ft_model.parameters()))
print("BF16 supported:", torch.cuda.is_bf16_supported())
print("Has scaler:", 'scaler' in dir())  # should ideally be False or unused

# import time
# import numpy as np
# import os
# import zipfile
# import shutil

# ft_model.train()
# global_step   = 0
# best_val_loss = float("inf")
# train_losses  = []
# ZIP_EVERY_EPOCHS = 5

# optimizer.zero_grad()
# start_time = time.time()

# for epoch in range(1, NUM_EPOCHS + 1):
#     print(f"\n{'='*65}")
#     print(f"  EPOCH {epoch}/{NUM_EPOCHS}")
#     print(f"{'='*65}")

#     ft_model.train()
#     epoch_losses = []

#     for batch_idx, batch in enumerate(train_loader):
#         batch = {k: v.to(device) for k, v in batch.items()}

#         with torch.amp.autocast("cuda", dtype=torch.bfloat16):
#             outputs = ft_model(
#                 input_ids=              batch["desc_input_ids"],
#                 attention_mask=         batch["desc_attention_mask"],
#                 prompt_input_ids=       batch["input_ids"],
#                 prompt_attention_mask=  batch["attention_mask"],
#                 decoder_attention_mask= batch["decoder_attention_mask"],
#                 labels=                 batch["labels"],
#             )
#             loss = outputs.loss / GRAD_ACCUM_STEPS

#         loss.backward()

#         if (batch_idx + 1) % GRAD_ACCUM_STEPS == 0:
#             torch.nn.utils.clip_grad_norm_(
#                 [p for p in ft_model.parameters() if p.requires_grad],
#                 max_norm=1.0
#             )
#             optimizer.step()
#             scheduler.step()
#             optimizer.zero_grad()
#             global_step += 1
#             torch.cuda.empty_cache()

#             actual_loss = loss.item() * GRAD_ACCUM_STEPS
#             train_losses.append(actual_loss)
#             epoch_losses.append(actual_loss)

#             if global_step % 10 == 0:
#                 elapsed       = time.time() - start_time
#                 steps_per_sec = global_step / elapsed
#                 remaining     = (MAX_TRAIN_STEPS - global_step) / steps_per_sec / 60
#                 vram_gb       = torch.cuda.memory_allocated() / 1e9
#                 print(
#                     f"  Step {global_step:4d} | "
#                     f"Loss: {actual_loss:.4f} | "
#                     f"LR: {scheduler.get_last_lr()[0]:.2e} | "
#                     f"VRAM: {vram_gb:.1f}GB | "
#                     f"ETA: {remaining:.1f}min"
#                 )

#     # ── End of epoch: log avg train loss ─────────────────────────────
#     avg_train_loss = np.mean(epoch_losses) if epoch_losses else float("nan")
#     print(f"\n  Epoch {epoch} avg train loss: {avg_train_loss:.4f}")

#     # ── Validation every SAVE_EVERY_EPOCHS ───────────────────────────
#     if epoch % SAVE_EVERY_EPOCHS == 0:
#         ft_model.eval()
#         val_losses = []
#         with torch.no_grad():
#             for val_batch in val_loader:
#                 val_batch = {k: v.to(device) for k, v in val_batch.items()}
#                 with torch.amp.autocast("cuda", dtype=torch.bfloat16):
#                     val_out = ft_model(
#                         input_ids=              val_batch["desc_input_ids"],
#                         attention_mask=         val_batch["desc_attention_mask"],
#                         prompt_input_ids=       val_batch["input_ids"],
#                         prompt_attention_mask=  val_batch["attention_mask"],
#                         decoder_attention_mask= val_batch["decoder_attention_mask"],
#                         labels=                 val_batch["labels"],
#                     )
#                     val_losses.append(val_out.loss.item())

#         val_loss = np.mean(val_losses)
#         print(f"  📊 Epoch {epoch} | Val Loss: {val_loss:.4f}")

#         if val_loss < best_val_loss:
#             best_val_loss = val_loss
#             ckpt_dir = "./best_checkpoint"
#             ft_model.save_pretrained(ckpt_dir)
#             ft_tokenizer.save_pretrained(ckpt_dir)
#             ft_desc_tokenizer.save_pretrained(ckpt_dir + "/desc_tokenizer")
#             print(f"  💾 New best! val_loss={best_val_loss:.4f} → saved to {ckpt_dir}")

#         ft_model.train()
#         torch.cuda.empty_cache()

#     # ── Periodic zip every ZIP_EVERY_EPOCHS ──────────────────────────
#     if epoch % ZIP_EVERY_EPOCHS == 0:
#         periodic_ckpt_dir = f"./checkpoint_epoch_{epoch}"
#         ft_model.eval()
#         ft_model.save_pretrained(periodic_ckpt_dir)
#         ft_tokenizer.save_pretrained(periodic_ckpt_dir)
#         ft_desc_tokenizer.save_pretrained(periodic_ckpt_dir + "/desc_tokenizer")
#         torch.save({
#             "epoch":          epoch,
#             "global_step":    global_step,
#             "optimizer":      optimizer.state_dict(),
#             "scheduler":      scheduler.state_dict(),
#             "best_val_loss":  best_val_loss,
#             "train_losses":   train_losses,
#         }, os.path.join(periodic_ckpt_dir, "training_state.pt"))
#         zip_checkpoint(periodic_ckpt_dir, f"epoch_{epoch}")
#         shutil.rmtree(periodic_ckpt_dir)
#         ft_model.train()

#         torch.cuda.empty_cache()

# print("\n" + "=" * 65)
# print("🎉 FINETUNING COMPLETE")
# print(f"   Total epochs : {NUM_EPOCHS}")
# print(f"   Total steps  : {global_step}")
# print(f"   Best val loss: {best_val_loss:.4f}")
# print(f"   Time taken   : {(time.time() - start_time)/60:.1f} min")
# print("=" * 65)


#code up wan't saving at 0.25 epochs


import time
import numpy as np
import os
import zipfile
import shutil

# ── Blackwell-specific (add here) ─────────────────────────────────────────
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.set_float32_matmul_precision('high')
ft_model = torch.compile(ft_model, mode="reduce-overhead")
# ──────────────────────────────────────────────────────────────────────────

ft_model.train()
global_step   = 0
best_val_loss = float("inf")
train_losses  = []

optimizer.zero_grad()
start_time = time.time()

for epoch in range(1, NUM_EPOCHS + 1):
    print(f"\n{'='*65}")
    print(f"  EPOCH {epoch}/{NUM_EPOCHS}")
    print(f"{'='*65}")

    ft_model.train()
    epoch_losses = []

    for batch_idx, batch in enumerate(train_loader):
        batch = {k: v.to(device) for k, v in batch.items()}

        # with torch.amp.autocast("cuda", dtype=torch.bfloat16):
        with torch.amp.autocast("cuda", dtype=torch.float8_e4m3fn):
            outputs = ft_model(
                input_ids=              batch["desc_input_ids"],
                attention_mask=         batch["desc_attention_mask"],
                prompt_input_ids=       batch["input_ids"],
                prompt_attention_mask=  batch["attention_mask"],
                decoder_attention_mask= batch["decoder_attention_mask"],
                labels=                 batch["labels"],
            )
            loss = outputs.loss / GRAD_ACCUM_STEPS

        loss.backward()

        # ── Optimizer Step ────────────────────────────────────────────────
        if (batch_idx + 1) % GRAD_ACCUM_STEPS == 0:
            torch.nn.utils.clip_grad_norm_(
                [p for p in ft_model.parameters() if p.requires_grad],
                max_norm=1.0
            )
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()
            global_step += 1

            actual_loss = loss.item() * GRAD_ACCUM_STEPS
            train_losses.append(actual_loss)
            epoch_losses.append(actual_loss)

            # ── Logging ───────────────────────────────────────────────────
            if global_step % 10 == 0:
                elapsed       = time.time() - start_time
                steps_per_sec = global_step / max(elapsed, 1e-9)
                remaining     = (MAX_TRAIN_STEPS - global_step) / max(steps_per_sec, 1e-9) / 60
                vram_gb       = torch.cuda.memory_allocated() / 1e9
                print(
                    f"  Step {global_step:4d} | "
                    f"Loss: {actual_loss:.4f} | "
                    f"LR: {scheduler.get_last_lr()[0]:.2e} | "
                    f"VRAM: {vram_gb:.1f}GB | "
                    f"ETA: {remaining:.1f}min"
                )
                wandb.log({
                    "train/loss":        actual_loss,
                    "train/lr":          scheduler.get_last_lr()[0],
                    "train/vram_gb":     vram_gb,
                    "train/global_step": global_step,
                }, step=global_step)

            # ── Validation & Best Checkpoint ──────────────────────────────
            if global_step % SAVE_STEPS == 0 and global_step > 0:
                ft_model.eval()
                val_losses = []
                with torch.no_grad():
                    for val_batch in val_loader:
                        val_batch = {k: v.to(device) for k, v in val_batch.items()}
                        # with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                        with torch.amp.autocast("cuda", dtype=torch.float8_e4m3fn):
                            val_out = ft_model(
                                input_ids=              val_batch["desc_input_ids"],
                                attention_mask=         val_batch["desc_attention_mask"],
                                prompt_input_ids=       val_batch["input_ids"],
                                prompt_attention_mask=  val_batch["attention_mask"],
                                decoder_attention_mask= val_batch["decoder_attention_mask"],
                                labels=                 val_batch["labels"],
                            )
                            val_losses.append(val_out.loss.item())

                val_loss = np.mean(val_losses)
                print(f"\n  📊 Step {global_step} | Val Loss: {val_loss:.4f}")

                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    ft_model.save_pretrained(ckpt_dir)
                    ft_tokenizer.save_pretrained(ckpt_dir)
                    ft_desc_tokenizer.save_pretrained(ckpt_dir + "/desc_tokenizer")
                    print(f"  💾 New best! val_loss={best_val_loss:.4f} → saved to {ckpt_dir}")

                wandb.log({
                    "val/loss":       val_loss,
                    "val/best_loss":  best_val_loss,
                }, step=global_step)


                ft_model.train()

            # ── Periodic Full Checkpoint + Zip ────────────────────────────
            if global_step % ZIP_EVERY_STEPS == 0 and global_step > 0:

                periodic_ckpt_dir = f"{ckpt_dir}/checkpoint_step_{global_step}"
                ft_model.eval()
                ft_model.save_pretrained(periodic_ckpt_dir)
                ft_tokenizer.save_pretrained(periodic_ckpt_dir)
                ft_desc_tokenizer.save_pretrained(periodic_ckpt_dir + "/desc_tokenizer")

                # Save training state
                torch.save({
                    "epoch":          epoch,
                    "global_step":    global_step,
                    "optimizer":      optimizer.state_dict(),
                    "scheduler":      scheduler.state_dict(),
                    "best_val_loss":  best_val_loss,
                    "train_losses":   train_losses,
                }, os.path.join(periodic_ckpt_dir, "training_state.pt"))

                # Inline zip to avoid missing function errors
                zip_name = f"{ckpt_dir}/checkpoint_step_{global_step}.zip"
                print(f"  🗜️ Zipping → {zip_name} ...")
                with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as zf:
                    for root, dirs, files in os.walk(periodic_ckpt_dir):
                        for file in files:
                            file_path = os.path.join(root, file)
                            arcname   = os.path.relpath(file_path, start=os.path.dirname(periodic_ckpt_dir))
                            zf.write(file_path, arcname)
                print(f"  ✅ Saved {zip_name} ({os.path.getsize(zip_name)/1e6:.1f} MB)")

                shutil.rmtree(periodic_ckpt_dir)
                ft_model.train()

            torch.cuda.empty_cache()  # Keep VRAM stable during long runs

    # ── End of epoch: log avg train loss ──────────────────────────────────
    avg_train_loss = np.mean(epoch_losses) if epoch_losses else float("nan")
    print(f"\n  Epoch {epoch} avg train loss: {avg_train_loss:.4f}")

wandb.finish()

print("\n" + "=" * 65)
print("🎉 FINETUNING COMPLETE")
print(f"   Total epochs : {NUM_EPOCHS}")
print(f"   Total steps  : {global_step}")
print(f"   Best val loss: {best_val_loss:.4f}")
print(f"   Time taken   : {(time.time() - start_time)/60:.1f} min")
print("=" * 65)

# import time
# import numpy as np
# import os
# import zipfile
# import shutil

# print("=" * 65)
# print("🏋️  STARTING FINETUNING")
# print("=" * 65)

# ft_model.train()
# global_step   = 0
# best_val_loss = float("inf")
# train_losses  = []

# optimizer.zero_grad()
# start_time = time.time()
# epoch = 0

# ZIP_EVERY_STEPS = 1000  # ← zip checkpoint every N steps

# def zip_checkpoint(ckpt_dir, step):
#     """Zip a checkpoint directory and return the zip filename."""
#     zip_name = f"checkpoint_step_{step}.zip"
#     print(f"  🗜️  Zipping checkpoint → {zip_name} ...")
#     with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as zf:
#         for root, dirs, files in os.walk(ckpt_dir):
#             for file in files:
#                 file_path = os.path.join(root, file)
#                 arcname   = os.path.relpath(file_path, start=os.path.dirname(ckpt_dir))
#                 zf.write(file_path, arcname)
#     size_mb = os.path.getsize(zip_name) / 1e6
#     print(f"  ✅  Saved {zip_name} ({size_mb:.1f} MB)\n")
#     return zip_name

# while global_step < MAX_TRAIN_STEPS:
#     epoch += 1
#     for batch_idx, batch in enumerate(train_loader):
#         if global_step >= MAX_TRAIN_STEPS:
#             break

#         batch = {k: v.to(device) for k, v in batch.items()}

#         # ── Forward with bfloat16 AMP ─────────────────────────────────────
#         with torch.amp.autocast("cuda", dtype=torch.bfloat16):
#             outputs = ft_model(
#                 input_ids=              batch["desc_input_ids"],
#                 attention_mask=         batch["desc_attention_mask"],
#                 prompt_input_ids=       batch["input_ids"],
#                 prompt_attention_mask=  batch["attention_mask"],
#                 decoder_attention_mask= batch["decoder_attention_mask"],
#                 labels=                 batch["labels"],
#             )
#             loss = outputs.loss / GRAD_ACCUM_STEPS

#         # ── Backward (no scaler needed for bfloat16) ──────────────────────
#         loss.backward()

#         # ── Gradient accumulation step ────────────────────────────────────
#         if (batch_idx + 1) % GRAD_ACCUM_STEPS == 0:
#             torch.nn.utils.clip_grad_norm_(
#                 [p for p in ft_model.parameters() if p.requires_grad],
#                 max_norm=1.0
#             )
#             optimizer.step()
#             scheduler.step()
#             optimizer.zero_grad()
#             global_step += 1
#             torch.cuda.empty_cache()

#             actual_loss = loss.item() * GRAD_ACCUM_STEPS
#             train_losses.append(actual_loss)

#             if global_step % 10 == 0:
#                 elapsed       = time.time() - start_time
#                 steps_per_sec = global_step / elapsed
#                 remaining     = (MAX_TRAIN_STEPS - global_step) / steps_per_sec / 60
#                 vram_gb       = torch.cuda.memory_allocated() / 1e9
#                 print(
#                     f"  Step {global_step:4d}/{MAX_TRAIN_STEPS} | "
#                     f"Loss: {actual_loss:.4f} | "
#                     f"LR: {scheduler.get_last_lr()[0]:.2e} | "
#                     f"VRAM: {vram_gb:.1f}GB | "
#                     f"ETA: {remaining:.1f}min"
#                 )

#         # ── Validation + checkpoint ───────────────────────────────────────
#         if (
#             global_step % SAVE_STEPS == 0
#             and global_step > 0
#             and (batch_idx + 1) % GRAD_ACCUM_STEPS == 0
#         ):
#             ft_model.eval()
#             val_losses = []
#             with torch.no_grad():
#                 for val_batch in val_loader:
#                     val_batch = {k: v.to(device) for k, v in val_batch.items()}
#                     with torch.amp.autocast("cuda", dtype=torch.bfloat16):
#                         val_out = ft_model(
#                             input_ids=              val_batch["desc_input_ids"],
#                             attention_mask=         val_batch["desc_attention_mask"],
#                             prompt_input_ids=       val_batch["input_ids"],
#                             prompt_attention_mask=  val_batch["attention_mask"],
#                             decoder_attention_mask= val_batch["decoder_attention_mask"],
#                             labels=                 val_batch["labels"],
#                         )
#                         val_losses.append(val_out.loss.item())

#             val_loss = np.mean(val_losses)
#             print(f"\n  📊 Step {global_step} | Val Loss: {val_loss:.4f}")

#             if val_loss < best_val_loss:
#                 best_val_loss = val_loss
#                 ckpt_dir = "./best_checkpoint"
#                 ft_model.save_pretrained(ckpt_dir)
#                 ft_tokenizer.save_pretrained(ckpt_dir)
#                 ft_desc_tokenizer.save_pretrained(ckpt_dir + "/desc_tokenizer")
#                 print(f"  💾 New best! val_loss={best_val_loss:.4f} → saved to {ckpt_dir}\n")

#             ft_model.train()
#             torch.cuda.empty_cache()

#         # ── Periodic zip every ZIP_EVERY_STEPS ───────────────────────────
#         if (
#             global_step % ZIP_EVERY_STEPS == 0
#             and global_step > 0
#             and (batch_idx + 1) % GRAD_ACCUM_STEPS == 0
#         ):
#             periodic_ckpt_dir = f"./checkpoint_step_{global_step}"
#             ft_model.eval()
#             ft_model.save_pretrained(periodic_ckpt_dir)
#             ft_tokenizer.save_pretrained(periodic_ckpt_dir)
#             ft_desc_tokenizer.save_pretrained(periodic_ckpt_dir + "/desc_tokenizer")

#             # Save training state alongside model weights
#             torch.save({
#                 "global_step":    global_step,
#                 "optimizer":      optimizer.state_dict(),
#                 "scheduler":      scheduler.state_dict(),
#                 "best_val_loss":  best_val_loss,
#                 "train_losses":   train_losses,
#             }, os.path.join(periodic_ckpt_dir, "training_state.pt"))

#             zip_checkpoint(periodic_ckpt_dir, global_step)

#             # Remove unzipped dir to save disk space
#             shutil.rmtree(periodic_ckpt_dir)
#             ft_model.train()
#             torch.cuda.empty_cache()

# print("\n" + "=" * 65)
# print("🎉 FINETUNING COMPLETE")
# print(f"   Total steps  : {global_step}")
# print(f"   Best val loss: {best_val_loss:.4f}")
# print(f"   Time taken   : {(time.time() - start_time)/60:.1f} min")
# print("=" * 65)

"""## 8. Training Loss Plot"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))
plt.plot(train_losses, alpha=0.5, color="steelblue", label="Train Loss (raw)")
if len(train_losses) > 20:
    window = 20
    smoothed = np.convolve(train_losses, np.ones(window)/window, mode="valid")
    plt.plot(range(window - 1, len(train_losses)), smoothed,
             color="darkorange", linewidth=2, label=f"Smoothed (w={window})")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.title("Finetuning Loss — Indic Parler TTS (Nepali, v3)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("training_loss.png", dpi=150)
plt.show()
print("💾 Saved training_loss.png")

"""## 9. Push to HuggingFace Hub"""

import gc
from parler_tts import ParlerTTSForConditionalGeneration

print("Loading best checkpoint...")
best_model = ParlerTTSForConditionalGeneration.from_pretrained("./best_checkpoint")
best_tok   = AutoTokenizer.from_pretrained("./best_checkpoint")
best_desc_tok = AutoTokenizer.from_pretrained("./best_checkpoint/desc_tokenizer")

print(f"Pushing to: {OUTPUT_REPO}")
best_model.push_to_hub(OUTPUT_REPO,
    commit_message=f"Nepali finetuned Indic Parler — best val_loss={best_val_loss:.4f}")
best_tok.push_to_hub(OUTPUT_REPO, commit_message="Prompt tokenizer")
best_desc_tok.push_to_hub(OUTPUT_REPO, commit_message="Description tokenizer")

print(f"\n✅ Pushed → https://huggingface.co/{OUTPUT_REPO}")

del best_model
gc.collect()
torch.cuda.empty_cache()

"""## 10. Inference Test"""

import soundfile as sf
import IPython.display as ipd
import numpy as np
import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer

print("Loading best checkpoint for inference...")
infer_model = ParlerTTSForConditionalGeneration.from_pretrained(
    "./best_checkpoint"
).to(device).eval()

# Load BOTH tokenizers from checkpoint
infer_prompt_tok = AutoTokenizer.from_pretrained("./best_checkpoint")
infer_desc_tok   = AutoTokenizer.from_pretrained("./best_checkpoint/desc_tokenizer")

TEST_TEXTS = [
    "नेपाल दक्षिण एसियामा अवस्थित एउटा सुन्दर देश हो।",
    "काठमाडौं नेपालको राजधानी र सबैभन्दा ठूलो सहर हो।",
    "मलाई नेपाली भाषा मन पर्छ।",
]
TEST_DESC = "A female speaker delivers clear Nepali speech at a normal pace. The recording is of very high quality."

for i, text in enumerate(TEST_TEXTS):
    print(f"\n[{i+1}] {text}")

    desc_ids   = infer_desc_tok(TEST_DESC, return_tensors="pt").input_ids.to(device)
    prompt_ids = infer_prompt_tok(text, return_tensors="pt").input_ids.to(device)

    with torch.inference_mode():
        gen = infer_model.generate(
            input_ids=desc_ids,
            prompt_input_ids=prompt_ids,
            do_sample=True,
            temperature=1.0,
            max_new_tokens=500,
        )

    audio = gen.cpu().numpy().squeeze().astype(np.float32)
    # Normalise to [-1, 1]
    max_val = np.abs(audio).max()
    if max_val > 1e-6:
        audio = audio / max_val

    fname = f"test_nepali_{i+1}.wav"
    sf.write(fname, audio, infer_model.config.sampling_rate)
    print(f"  💾 Saved: {fname}")
    ipd.display(ipd.Audio(audio, rate=infer_model.config.sampling_rate))

print("\n✅ Inference complete!")







