#!/usr/bin/env python3
"""Package the Nepali audio that is neither public nor in nepali-speech-archive,
and stream it to a second gated repo one shard at a time.

Why a streaming packager rather than `datasets.push_to_hub`: the largest source is
6,680 h of 48 kHz chunks, so the FLAC never fits on a staging disk at once. Each
shard is encoded, uploaded and deleted before the next begins, and `state.json`
records the manifest line reached, so a kill -9 costs one shard.

Source names are NOT uploaded. `src` carries an opaque code; the code -> directory
mapping lives only in dataset/SOURCE_CODES.md, the way id_map.jsonl already holds
the archive's id -> path mapping.

  python3 pack_reserve.py --list
  python3 pack_reserve.py --sources r3 --limit 40 --dry-run
  python3 pack_reserve.py --sources r1,r2,r3,r4,r5,r6
"""
from __future__ import annotations
import argparse, hashlib, io, json, os, re, subprocess, sys, time
from concurrent.futures import ThreadPoolExecutor

import pyarrow as pa
import pyarrow.parquet as pq
from huggingface_hub import HfApi

ROOT = "/workspace/proc_data_new"
STAGE = "/workspace/hf_stage_reserve"
REPO_PREFIX = os.environ.get("RESERVE_PREFIX", "milanakdj/nepali-audio-reserve")
def repo_of(code: str) -> str: return f"{REPO_PREFIX}-{code}"
ARCHIVE_IDMAP = "/root/tts/TTS_training/release/id_map.jsonl"
NEW_IDMAP = "/root/tts/TTS_training/release/id_map_reserve.jsonl"
SHARD_BYTES = int(os.environ.get("SHARD_BYTES", 900_000_000))
WORKERS = int(os.environ.get("PACK_WORKERS", 4))
NE = re.compile(r'"language": ?"(ne|nep|nepali|Nepali)"|/Nepali/')

# Smallest first, so the cheap sources are safely on the Hub before the 6,680 h one
# starts. The codes stay r1..r6 whatever the order -- they are published in the `src`
# column, so renumbering them would break dataset/SOURCE_CODES.md.
# One ordering constraint survives: r5 must precede r6, because the audiobook rows are
# a category:books view over the same chunk ids and the id dedupe keeps whichever lands
# first. Nothing without a transcript is listed, by instruction.
SOURCES = [
    ("r3", "orpheus_snr40-50",        "train/manifest.jsonl",        16.2),
    ("r4", "podcast-index",           "train/manifest.jsonl",        54.0),
    ("r2", "ncert_conversations",     "train/manifest.jsonl",       148.6),
    ("r5", "podcast-index-audiobook", "train/manifest.jsonl",       363.2),
    ("r1", "indicvoices-r-long",      "train/manifest_train.jsonl", 548.1),
    ("r6", "podcast-index-feeds-5min","train/manifest.jsonl",      6680.8),
]

CARDS = {
 "r1": ("Nepali long-form speech, restored", "548.1", "24 kHz",
        "One speaker per clip, average 32 s, up to several minutes.",
        "Derived from **AI4Bharat IndicVoices-R** (CC-BY-4.0) and restored with sidon-v0.1. "
        "Attribution is required by that licence, so it is given here. These are the long-form "
        "files our quality gate rejected; the 74 h that passed are in "
        "[`nepali-speech-archive`](https://huggingface.co/datasets/milanakdj/nepali-speech-archive) "
        "and are excluded here by exact path."),
 "r2": ("Nepali synthetic educational dialogue", "137.0", "24 kHz",
        "Two speakers per clip, 2-5 minutes, teacher/student turns.",
        "**Synthetic.** Generated by a TTS model reading NCERT-style educational dialogue, "
        "code-mixed Nepali/English. No human speaker is recorded here."),
 "r3": ("Nepali spontaneous short clips (SNR 40-50)", "16.2", "24 kHz",
        "Single speaker, 5-20 s, spontaneous.",
        "Derived from third-party web audio whose rights holders did not grant "
        "redistribution, which is why access is gated and the source is not named."),
 "r4": ("Nepali short clips, ASR-agreed transcripts", "53.9", "24 kHz",
        "Single speaker, 3-20 s.",
        "Transcripts kept only where three independent ASR systems agreed. Derived from "
        "third-party audio whose rights holders did not grant redistribution."),
 "r5": ("Nepali long-form single-speaker readings", "363.2", "48 kHz",
        "One speaker per clip, ~5 minute chunks.",
        "Derived from third-party published readings whose rights holders did not grant "
        "redistribution. Access is gated and the source is not named."),
 "r6": ("Nepali two-speaker conversation chunks", "6317.6", "48 kHz",
        "Two speakers per clip, ~5 minute diarized chunks.",
        "Derived from third-party audio whose rights holders did not grant redistribution. "
        "**The hour count is language-dominant, not monolingual**: a chunk labelled Nepali can "
        "carry substantial English or Hindi. `lang_sec` gives the per-row truth and is the only "
        "honest basis for filtering."),
}

CARD = """---
license: other
license_name: see-card
language:
- ne
task_categories:
- automatic-speech-recognition
- text-to-speech
tags:
- nepali
- speech
- backup
configs:
- config_name: default
  data_files:
  - split: train
    path: data/train-*.parquet
dataset_info:
  features:
  - name: id
    dtype: string
  - name: audio
    dtype: audio
  - name: text
    dtype: string
  - name: duration
    dtype: float32
  - name: spk
    dtype: string
  - name: src
    dtype: string
  - name: sr
    dtype: int32
  - name: ch
    dtype: int8
  - name: nspk
    dtype: int16
  - name: lang_sec
    dtype: string
  - name: segments
    dtype: string
  - name: dnsmos
    dtype: float32
  - name: snr_db
    dtype: float32
extra_gated_heading: Request access
extra_gated_prompt: |-
  Nepali speech that did not enter model training, kept as a backup. Part of this data is
  derived from third-party audio whose rights holders did not consent to redistribution,
  so access is granted on request.

  By requesting access you agree not to redistribute the audio, not to use it to clone or
  impersonate any identifiable speaker, and to treat the transcripts as machine-generated
  rather than authoritative.
extra_gated_fields:
  Name: text
  Affiliation: text
  What you intend to use this data for: text
  I will not redistribute the audio: checkbox
  I will not use this data to clone or impersonate any identifiable speaker: checkbox
extra_gated_button_content: Request access
---

# {title}

**~{hours} h of Nepali speech at {rate}.** {shape}

A **backup, not a release**: the transcripts are machine-generated, and none of this
audio passed the quality gate that produced our training corpus.

{prov}

## Columns

| column | contents |
|---|---|
| `id` | first 16 hex of `sha256(original path # offset)` |
| `audio` | FLAC, native sample rate preserved |
| `text` | transcript, machine-generated |
| `duration` | seconds |
| `spk` | 12 hex of `sha256(directory + speaker label)` -- groups speakers without naming them |
| `src` | opaque source code, constant within this repo |
| `sr`, `ch`, `nspk` | sample rate, channels, speaker count |
| `lang_sec` | JSON seconds per language, where the source measured it |
| `segments` | JSON segment or turn timings, where available |
| `dnsmos`, `snr_db` | quality metrics, where measured |

Paths, URLs, feed and episode identifiers, author names and raw diarization labels are
removed from every row.

## Companion repos

This is one of six sibling backups, split by source. The others carry different speech
shapes at `{prefix}-*`. Nothing overlaps: rows are deduplicated by audio path against
`nepali-speech-archive` and by chunk id across siblings.
"""

def write_card(api, code, dry):
    title, hours, rate, shape, prov = CARDS[code]
    body = CARD.format(title=title, hours=hours, rate=rate, shape=shape, prov=prov,
                       prefix=REPO_PREFIX)
    if dry: return
    path = f"{STAGE}/README-{code}.md"
    open(path, "w").write(body)
    api.upload_file(path_or_fileobj=path, path_in_repo="README.md", repo_id=repo_of(code),
                    repo_type="dataset", commit_message="Card")

SCHEMA = pa.schema([
    ("id", pa.string()),
    ("audio", pa.struct([("bytes", pa.binary()), ("path", pa.string())])),
    ("text", pa.string()),
    ("duration", pa.float32()),
    ("spk", pa.string()),
    ("src", pa.string()),
    ("sr", pa.int32()),
    ("ch", pa.int8()),
    ("nspk", pa.int16()),
    ("lang_sec", pa.string()),
    ("segments", pa.string()),
    ("dnsmos", pa.float32()),
    ("snr_db", pa.float32()),
])

def h16(s: str) -> str: return hashlib.sha256(s.encode()).hexdigest()[:16]
def h12(s: str) -> str: return hashlib.sha256(s.encode()).hexdigest()[:12]

def resolve(p: str | None):
    if not p: return None
    for c in (p, p.replace("/projects/data/ttsteam/proc_data_new/", f"{ROOT}/"),
              p.replace("/projects/data/ttsteam/", "/workspace/")):
        if os.path.isfile(c): return c
    return None

def archived_paths() -> set[str]:
    """Exact audio paths already in nepali-speech-archive -- 30,042 of the
    indicvoices-r-long files are there, so they must not be uploaded twice."""
    s = set()
    if os.path.isfile(ARCHIVE_IDMAP):
        with open(ARCHIVE_IDMAP, errors="replace") as f:
            for l in f:
                try: s.add(json.loads(l)["path"])
                except Exception: pass
    return s

def flac_bytes(src: str, off, dur, target_sr=None):
    """FLAC for one row. Rows carrying an offset name a whole episode -- one is
    28,422 s -- so those are cut, never read whole."""
    cmd = ["ffmpeg", "-nostdin", "-v", "error"]
    if off is not None and dur:
        cmd += ["-ss", f"{float(off):.3f}", "-t", f"{float(dur):.3f}"]
    cmd += ["-i", src]
    if target_sr: cmd += ["-ar", str(target_sr)]
    cmd += ["-c:a", "flac", "-compression_level", "5", "-f", "flac", "pipe:1"]
    p = subprocess.run(cmd, capture_output=True)
    return p.stdout if p.returncode == 0 and p.stdout else None

def row_of(d: dict, code: str, dirname: str):
    src = resolve(d.get("audio_filepath"))
    if not src: return None, None
    text = d.get("text") or d.get("normalised_text") or d.get("unnormalised_text")
    if not text or not str(text).strip(): return None, None       # no transcript, no upload
    off = d.get("offset") if d.get("offset") is not None else d.get("chunk_start_s")
    dur = float(d.get("duration") or 0)
    if dur <= 0: return None, None
    chunk_id = d.get("id") or d.get("key") or d.get("sample_id")
    uid = h16(f"{src}#{off if off is not None else 0}")
    spk_label = d.get("speaker_id") or (d.get("speakers") or [None])[0] or os.path.dirname(src)
    ls = d.get("language_seconds")
    segs = d.get("asr_segments") or d.get("turns")
    rec = dict(id=uid, text=str(text), duration=dur, spk=h12(f"{dirname}|{spk_label}"),
               src=code, sr=int(d.get("sample_rate") or 0), ch=int(d.get("channels") or 1),
               nspk=int(d.get("num_speakers") or 0),
               lang_sec=json.dumps(ls, ensure_ascii=False) if ls else None,
               segments=json.dumps(segs, ensure_ascii=False) if segs else None,
               dnsmos=d.get("dnsmos_ovrl_mean"), snr_db=d.get("snr_estimate_db"))
    return rec, dict(src_path=src, off=off, chunk_id=str(chunk_id) if chunk_id else None)

def main(a):
    if a.list:
        for c, d, mf, h in SOURCES: print(f"{c}  {d:28} ~{h:8.1f} h  {ROOT}/{d}/{mf}")
        return
    want = set(a.sources.split(",")) if a.sources else {c for c, *_ in SOURCES}
    os.makedirs(STAGE, exist_ok=True)
    api = HfApi(token=open("/root/.hf_milanakdj").read().strip())
    st_path = f"{STAGE}/state.json"
    st = json.load(open(st_path)) if os.path.isfile(st_path) else {"shards": {}, "srcs": {}, "ids": []}
    done_ids = set(st.get("ids", []))
    arch = archived_paths()
    print(f"[init] repos={REPO_PREFIX}-r1..r6 dry_run={a.dry_run} archived_paths={len(arch):,} "
          f"resume_shards={st['shards']} seen_ids={len(done_ids):,}", flush=True)

    buf, nbytes, cur = [], 0, None
    idmap = open(NEW_IDMAP, "a")

    def flush():
        nonlocal buf, nbytes
        if not buf or cur is None: return
        shard = st["shards"].get(cur, 0)
        repo = repo_of(cur)
        path = f"{STAGE}/train-{shard:05d}.parquet"
        pq.write_table(pa.Table.from_pylist(buf, schema=SCHEMA), path, compression="zstd")
        mb = os.path.getsize(path) / 1e6
        if a.dry_run:
            print(f"[shard] {os.path.basename(path)} {len(buf)} rows {mb:.0f} MB (kept, dry run)", flush=True)
        else:
            for attempt in range(4):
                try:
                    api.upload_file(path_or_fileobj=path, path_in_repo=f"data/{os.path.basename(path)}",
                                    repo_id=repo, repo_type="dataset",
                                    commit_message=f"shard {shard:05d}")
                    break
                except Exception as e:
                    print(f"[retry {attempt}] {type(e).__name__}: {str(e)[:200]}", flush=True)
                    time.sleep(30 * (attempt + 1))
            else:
                sys.exit(f"upload failed after retries: {path}")
            os.remove(path)
            print(f"[shard] {repo.split('/')[-1]} data/{os.path.basename(path)} "
                  f"{len(buf)} rows {mb:.0f} MB", flush=True)
        st["shards"][cur] = shard + 1
        buf, nbytes = [], 0
        st["ids"] = sorted(done_ids)
        json.dump(st, open(st_path, "w"))

    for code, dirname, mf, hours in SOURCES:
        if code not in want: continue
        path = f"{ROOT}/{dirname}/{mf}"
        if not os.path.isfile(path): print(f"!! {code} {dirname}: no manifest", flush=True); continue
        cur = code
        start = st["srcs"].get(code, 0)
        print(f"\n[src] {code} -> {repo_of(code)}  ~{hours} h  resume_line={start:,}", flush=True)
        if not a.dry_run:
            api.create_repo(repo_of(code), repo_type="dataset", private=False, exist_ok=True)
            api.update_repo_settings(repo_id=repo_of(code), repo_type="dataset", gated="manual")
            write_card(api, code, a.dry_run)
        kept = skipped = 0
        with open(path, errors="replace") as f, ThreadPoolExecutor(WORKERS) as pool:
            pending = []
            for lineno, line in enumerate(f):
                if lineno < start: continue
                if not NE.search(line): continue
                try: d = json.loads(line)
                except Exception: continue
                rec, loc = row_of(d, code, dirname)
                if not rec: skipped += 1; continue
                if loc["src_path"] in arch: skipped += 1; continue
                if rec["id"] in done_ids or (loc["chunk_id"] and loc["chunk_id"] in done_ids):
                    skipped += 1; continue
                done_ids.add(rec["id"])
                if loc["chunk_id"]: done_ids.add(loc["chunk_id"])
                pending.append((rec, loc, pool.submit(flac_bytes, loc["src_path"], loc["off"], rec["duration"], a.sr)))
                if len(pending) >= WORKERS * 4 or a.limit and kept + len(pending) >= a.limit:
                    for rec, loc, fut in pending:
                        b = fut.result()
                        if not b: skipped += 1; continue
                        rec["audio"] = {"bytes": b, "path": f"{rec['id']}.flac"}
                        buf.append(rec); nbytes += len(b); kept += 1
                        idmap.write(json.dumps({"id": rec["id"], "src": code,
                                                "path": loc["src_path"], "off": loc["off"]}) + "\n")
                    pending = []; idmap.flush()
                    st["srcs"][code] = lineno + 1
                    if nbytes >= SHARD_BYTES: flush()
                    if kept % 2000 < WORKERS * 4:
                        # st["shards"][code], not `shard` -- that name is local to
                        # flush(). The single-repo version had it in this scope; the
                        # split to six repos moved it and left this print unbound,
                        # which is a NameError the first time kept reaches 2000.
                        print(f"   {code} line {lineno:,} kept {kept:,} skipped {skipped:,} "
                              f"buf {nbytes/1e6:.0f} MB shard {st['shards'].get(code, 0)}",
                              flush=True)
                if a.limit and kept >= a.limit: break
            for rec, loc, fut in pending:
                b = fut.result()
                if not b: continue
                rec["audio"] = {"bytes": b, "path": f"{rec['id']}.flac"}
                buf.append(rec); nbytes += len(b); kept += 1
                # This tail drain must write id_map too. It did not, so the last
                # partial batch of every source was uploaded with no provenance
                # entry -- 14 rows of r3 and 15 of r4 went up untraceable. The
                # mapping is the only way back from an opaque id to a source path,
                # so a silent hole in it defeats the point of the opaque codes.
                idmap.write(json.dumps({"id": rec["id"], "src": code,
                                        "path": loc["src_path"], "off": loc["off"]}) + "\n")
            idmap.flush()
        flush()                     # never mix two sources in one shard
        print(f"[src] {code} done: kept {kept:,} skipped {skipped:,} "
              f"shards {st['shards'].get(code, 0)}", flush=True)
        json.dump(st, open(st_path, "w"))
    flush()
    idmap.close()
    if not a.dry_run:
        for code in want:
            i = api.dataset_info(repo_of(code), expand=["gated"])
            print(f"  {repo_of(code)}  gated={i.gated}  shards={st['shards'].get(code, 0)}", flush=True)
    print("[done]", flush=True)

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--sources"); p.add_argument("--limit", type=int)
    p.add_argument("--sr", type=int, help="resample everything to this rate (omit to keep native)")
    p.add_argument("--dry-run", action="store_true"); p.add_argument("--list", action="store_true")
    main(p.parse_args())
